chore: declare a dependency on aspect_rules_js
When I try to use `web_assets` with `bzlmod` I get the following error.

```
ERROR: error loading package under directory 'server/storyboard/ui': error loading package 'server/storyboard/ui': at /home/vscode/.cache/bazel/_bazel_vscode/7ad25f9ef7ff83782d7cbcac3c95dbb7/external/com_github_benchsci_rules_nodejs_gazelle+/defs.bzl:8:6: at /home/vscode/.cache/bazel/_bazel_vscode/7ad25f9ef7ff83782d7cbcac3c95dbb7/external/com_github_benchsci_rules_nodejs_gazelle+/internal/web_assets.bzl:6:6: Unable to find package for @@[unknown repo 'aspect_rules_js' requested from @@com_github_benchsci_rules_nodejs_gazelle+]//js:defs.bzl: The repository '@@[unknown repo 'aspect_rules_js' requested from @@com_github_benchsci_rules_nodejs_gazelle+]' could not be resolved: No repository visible as '@aspect_rules_js' from repository '@@com_github_benchsci_rules_nodejs_gazelle+'.
```

I get this error even when I add a dependency on aspect_rules_js to my `MODULE.bazel`. I think the root cause is a missing dependency on `aspect_rules_js` in this module, but I'm not a Bazel expert and might be mistaken. Let me know if this change will fix my problem.